= 2014年工作总结
徐浩洋

== 制冷组工作

2014年上半年我继续在制冷组负责与 UNDP 的联系以及报告和计划的编写工作，主要的工作内容包括：

=== 工商制冷行业 HPMP 2013年年度进展报告

报告按照 UNDP 提供的模板编写，分为背景、主要成果、项目管理监督、财务管理、建议意见等几个主要部分，其中主要成果、财务管理、建议意见等部分更新较多。报告介绍了项目在2013年开展的活动以及取得的进展，并更新了支付情况。报告是通过向组内有关同事咨询和收集数据写成的，获得了 UNDP 项目官员的好评。

=== 工商制冷行业 HPMP 项目文件更新

工商制冷行业 HPMP 之前的项目文件只涵盖了到2013年为止的资金拨付方案，我与制冷组同事和 UNDP 项目经理合作协商，编制了一版更新文件。

=== 双年工作计划更新

和项目文件的更新工作同时，在 UNDP 的监督下对双年工作计划进行了更新，调整了活动和预算，使其与当前工作进展和未来的工作安排一致。

=== 其他工作

参加合同审评委员会对行业计划下核查服务采购的讨论。

=== 感想

2014年1-5月，在制冷组的工作主要是协调工作，具体的项目开发和在执行项目管理工作做得较少。这主要与公益项目的工作牵扯时间精力有关，也有领导对个人工作量统筹安排的影响。但进展报告和工作计划等文件是 UNDP 管理我方项目，安排支付等工作的重要依据，准备文件时需要细心并多与同事和 UNDP 沟通。UNDP 的文件需要自己改的东西较多，文件之间的依赖关系多而复杂，要在双方之间数次往复，准备起来需要比较多的耐心，但熟练后应该能够比较快地完成。

== 泡沫组工作

=== 在执行项目日常管理工作

2014年5月起，我开始逐步接替李宇宸，参与聚氨酯泡沫行业HCFC淘汰示范项目和行业管理计划的管理工作。占工作量绝大部分的是在执行项目的管理工作，包括采购计划的更新、支付申请的审核、企业现场核查等。通过在工作中学习，从赠款协议、执行计划和合同中了解这部分工作的逻辑后，这部分工作的步骤也就显得非常直观，主要需要注意的是需要更加细心。目前这部分工作主要的问题是部分企业进展较慢，原因包括行政许可没有按时取得、企业担心转产不能顺利过渡而正在观望等。随着行业转用替代技术的趋势日渐明朗，这些问题应能得到克服。目前使用全水技术的企业多数已完成合同，使用环戊烷发泡技术的企业中，第一批31家多数已完成设备安装调试，第二、第三批的多数企业也已完成采购工作。

=== 与世界银行的协调工作

这部分工作包括向世界银行转送企业关于采购的请求和问题，修改采购计划，提交半年进展报告和工作计划，陪同世行人员到企业了解项目执行情况等。接手工作至今，共对采购计划进行了30处修改，并补充了大部分采购项目的日期、金额等信息。半年进展报告和工作计划均按照世界银行的时间和质量要求提交。企业提出的关于项目采购、资金分配等问题我均及时转达给世行以获取其意见，并在协会的帮助下将信息传达给企业。

和 UNDP 相比，世界银行的数据要求和管理的粒度较细，在项目多的时候令人感觉工作量比较大，但各种规程建立得比较完善，要求明确，一般提交时就能对文件还需要什么样的修改建立正确的预期。

=== 技术援助活动

我编写了在部分子行业内制定技术标准的工作大纲，已经提交给世界银行审批。我还参与了聚氨酯泡沫安全标准的编制和修改工作。

为方便2014年新签合同的管理，我编制了国内执行机构2014年度工作大纲，已经交给世行审批。

2014年底我还分别草拟了地方监测项目和技术支持中心的工作大纲，正在和同事讨论修改。

一期 HPMP 的投资活动合同已经接近签署完毕，而技术援助活动影响到替代技术的推广以及中小企业参与二期项目的意愿和能力。在一期 HPMP 执行的最后一年，技术援助活动的开展应当成为工作的重点，以保证一期项目的顺利结束和二期项目的顺利开展。

=== 二期项目准备

我编制了使用二期项目准备金开展行业调研和编制 PU HPMP 二期计划的项目建议书，并在世行项目官员来华访问期间与世行一同对建议书进行了修改。建议书随后在第73次执委会上获得通过。

== 公益项目

=== 外部专家选择

2014年初，为了推进 HCFC 替代技术指南的编制工作，需要通过个人专家选择选取泡沫、清洗行业专家各一位，参与指南内容的编写。通过向有关工作组同事了解信息，我在每个行业都选取了3名专家，并参与和组织了评选工作。中心与专家签署合同后，我继续负责对专家的联络和支付工作。

为了加强对美国环保署 SNAP 项目的研究，项目聘请外部专家进行 SNAP 的有关政策、实施方式和影响的研究。我编制了工作大纲并联系了候选专家，经个人专家选择与家电协会王雷理事长签订了合同。

由于项目资金有限和从事有关研究的专家较少，编制候选专家名单的时候遇到一些困难，但通过与同事的沟通和联系其他专家解决了这些问题。

=== 研究进展跟踪

围绕替代技术指南的编写，我定期对专家的工作进度进行跟踪，并组织会议以便课题组和外部专家交流研究进展和成果。

=== 项目协调

项目协调工作主要包括搜集项目支付和进展信息，报送有关数据，编写进展报告并提交到部科技司等。项目于2014年接受了中期检查，我准备了项目绩效自评估报告和财务报表，并从协作单位处搜集了相关报告并整合。项目在中期检查中被评为“优”级。

== 2015年计划

=== 泡沫行业

完成主要技援项目的合同签署工作。

编制二期项目计划。

完成示范项目收尾工作。

完成多数在执行项目的ICC支付工作。

=== 公益项目

开展替代品推荐目录编制活动。

完成替代技术指南。

开展科普作品编制活动。

开展政策建议编制活动。
