= 2014年工作总结
徐浩洋
2015.01.06
:revealjs_theme: solarized

== 总结内容

* 制冷组工作
* 泡沫组工作
* 公益项目工作
* 2015年工作想法

== 制冷组工作

2014年上半年我主要在制冷组负责与 UNDP 的联系以及报告和计划的编写工作。

* 工商制冷行业 HPMP 2013年年度进展报告
* 工商制冷行业 HPMP 项目文件更新
* 双年工作计划更新
* 其他工作

[NOTE.speaker]
--
- 报告按照 UNDP 提供的模板编写，分为背景、主要成果、项目管理监督、财务管理、建议意见等几个主要部分，其中主要成果、财务管理、建议意见等部分更新较多。报告介绍了项目在2013年开展的活动以及取得的进展，并更新了支付情况。报告是通过向组内有关同事咨询和收集数据写成的，获得了 UNDP 项目官员的好评。
- 工商制冷行业 HPMP 之前的项目文件只涵盖了到2013年为止的资金拨付方案，我与制冷组同事和 UNDP 项目经理合作协商，编制了一版更新文件。
- 和项目文件的更新工作同时，在 UNDP 的监督下对双年工作计划进行了更新，调整了活动和预算，使其与当前工作进展和未来的工作安排一致。
- 参加合同审评委员会对行业计划下核查服务采购的讨论。
--

== 感想

- 具体项目↓
- APR，TYWP，CDR……
- 熟练度↑

== 泡沫组工作

=== 在执行项目日常管理

- 采购计划更新
- 支付申请审核
- 企业现场核查

[ALERT]
从赠款协议、执行计划和合同中了解工作逻辑。

[NOTE]
目前使用全水技术的企业多数已完成合同，使用环戊烷发泡技术的企业中，第一批31家多数已完成设备安装调试，第二、第三批的多数企业也已完成采购工作。

=== 与世界银行协调

- 转达企业请求和问题
- 半年进展报告和工作计划
- 陪同世行现场调研

[NOTE]
和 UNDP 相比，世界银行的数据要求和管理的粒度较细，在项目多的时候令人感觉工作量比较大，但各种规程建立得比较完善，要求明确，一般提交时就能对文件还需要什么样的修改建立正确的预期。

=== 技术援助活动

- 技术标准工作大纲
- 安全标准工作大纲
- 国内执行机构2014年工作大纲
- 地方监测项目工作大纲
- 技术支持中心工作大纲

[NOTE]
一期 HPMP 的投资活动合同已经接近签署完毕，而技术援助活动影响到替代技术的推广以及中小企业参与二期项目的意愿和能力。在一期 HPMP 执行的最后一年，技术援助活动的开展应当成为工作的重点，以保证一期项目的顺利结束和二期项目的顺利开展。

=== 二期项目准备

编制了使用二期项目准备金开展行业调研和编制 PU HPMP 二期计划的项目建议书，并在世行项目官员来华访问期间与世行一同对建议书进行了修改。建议书随后在第73次执委会上获得通过。

== 公益项目

=== 外部专家选择

- 泡沫
- 清洗

通过接触专家也对行业增加了了解。

- SNAP

[NOTE]
事实证明实践经验对于了解政策系统十分有用。

=== 研究进展跟踪

- 通过电话邮件了解进展
- 组织会议方便交流

=== 项目协调

- 搜集项目财务和进度信息
- 定期报送数据
- 准备中期检查材料

== 2015年工作思路

- 适当调整工作重心到技术援助活动
- 推动替代技术评估方法成果总结和转化
